name: Run Techno Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/55 * * * *'

jobs:
  run_soul_workflow:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: binary by @Techno
        run: chmod +x devil
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot flask aiogram python-telegram-bot pymongo aiohttp
          pip install psutil
          pip install pytz

      - name: Run Techno.py
        run: python3 Techno.py
        
